version: '2'

services: 
  base_server:
    build: .
    image: shintech/base_server:latest
    container_name: base_server
    env_file:
      - ./base_server.env
    links:
      - db       
    ports:
      - 55460:55460
    restart: always
  db:
    image: shintech/database:latest
    container_name: base_server_db